# Vivado 2023.2 IP packaging entry for the SmolVLM2 reusable accelerator.
# Run from repo root:
# /data/home/songqiangxu/Xilinx/2023.2/Vivado/2023.2/bin/vivado \
#   -mode batch \
#   -source vivado/scripts/package_accelerator_ip.tcl \
#   -journal vivado/logs/package_accelerator_ip.jou \
#   -log vivado/logs/package_accelerator_ip.log

set script_dir [file dirname [file normalize [info script]]]
set repo_root [file normalize [file join $script_dir "../.."]]
set rtl_dir [file join $repo_root "SPINAL/vivado"]
set work_dir [file join $repo_root "vivado/work/package_accelerator_ip"]
set ip_repo_dir [file join $repo_root "vivado/ip_repo"]
set ip_root_dir [file join $ip_repo_dir "smolvlm2_accelerator_1_0"]
set report_dir [file join $repo_root "vivado/reports"]

file delete -force $work_dir
file delete -force $ip_root_dir
file mkdir $work_dir
file mkdir $ip_repo_dir
file mkdir $report_dir

create_project vlm_accel_ip_pack $work_dir -part xck26-sfvc784-2LV-c -force
set kv260_board_part [get_board_parts -quiet xilinx.com:kv260_som:part0:1.4]
if {$kv260_board_part ne ""} {
  set_property board_part $kv260_board_part [current_project]
}
set_property target_language Verilog [current_project]

# 这里直接打包 Spinal 生成的顶层和 HLS 黑盒聚合 RTL；.dat 是 ROM 初始化文件，
# 必须和 RTL 一起进入 IP 仓库，避免 Vivado 综合时找不到 $readmemh 依赖。
set rtl_files [list \
  [file join $rtl_dir "ACCELERATOR_replaced.v"] \
  [file join $rtl_dir "ACCELERATOR_bb_replaced.v"] \
]
add_files -norecurse $rtl_files
set dat_files [glob -nocomplain [file join $rtl_dir "*.dat"]]
if {[llength $dat_files] > 0} {
  add_files -norecurse $dat_files
}
set_property top ACCELERATOR [current_fileset]
update_compile_order -fileset sources_1

ipx::package_project \
  -root_dir $ip_root_dir \
  -vendor user.org \
  -library user \
  -taxonomy /UserIP \
  -import_files \
  -set_current true \
  -force

set core [ipx::current_core]
set_property name smolvlm2_accelerator $core
set_property display_name {SmolVLM2 Reuse Accelerator} $core
set_property description {Mode-aware SmolVLM2 LLM/ViT reusable accelerator generated by SpinalHDL and HLS.} $core

# 顶层端口命名遵循 AXI channel 后缀，Vivado 可据此自动推导 AXI-Lite 和多个 AXI master。
# 若后续 Spinal 改端口名，需要同步这里并重新检查 package IP 的 Ports and Interfaces。
ipx::infer_bus_interfaces \
  {xilinx.com:interface:aximm:1.0 xilinx.com:signal:clock:1.0 xilinx.com:signal:reset:1.0} \
  $core

foreach bus_if [ipx::get_bus_interfaces -of_objects $core] {
  set name [get_property NAME $bus_if]
  if {$name ne "" && $name ne "clk" && $name ne "resetn"} {
    catch {ipx::associate_bus_interfaces -busif $name -clock clk $core}
  }
}

set axilite_if [lindex [ipx::get_bus_interfaces axilite -of_objects $core] 0]
if {$axilite_if ne ""} {
  catch {
    ipx::add_memory_map axilite $core
    set_property slave_memory_map_ref axilite $axilite_if
    ipx::add_address_block reg0 [ipx::get_memory_maps axilite -of_objects $core]
    set_property range 65536 [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps axilite -of_objects $core]]
    set_property width 64 [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps axilite -of_objects $core]]
  }
}

ipx::update_checksums $core
ipx::save_core $core
set integrity_report [file join $report_dir "package_accelerator_ip_integrity.rpt"]
ipx::check_integrity -quiet $core
report_property $core -file [file join $report_dir "package_accelerator_ip_core.rpt"]
puts "VLM_VIVADO_IP_REPO=$ip_repo_dir"
puts "VLM_VIVADO_IP_ROOT=$ip_root_dir"
